module io.github.ititus.commons {
    requires transitive java.net.http;

    exports io.github.ititus.data;
    exports io.github.ititus.data.mutable;
    exports io.github.ititus.data.pair;
    exports io.github.ititus.function;
    exports io.github.ititus.io;
    exports io.github.ititus.math.base;
    exports io.github.ititus.math.base.binary;
    exports io.github.ititus.math.calculation;
    exports io.github.ititus.math.expression;
    exports io.github.ititus.math.function;
    exports io.github.ititus.math.function.constant;
    exports io.github.ititus.math.function.exponential;
    exports io.github.ititus.math.function.polynomial;
    exports io.github.ititus.math.function.trigonometric;
    exports io.github.ititus.math.graph;
    exports io.github.ititus.math.graph.algorithm;
    exports io.github.ititus.math.hash;
    exports io.github.ititus.math.matrix;
    exports io.github.ititus.math.modulus;
    exports io.github.ititus.math.number;
    exports io.github.ititus.math.permutation;
    exports io.github.ititus.math.quaternion;
    exports io.github.ititus.math.random;
    exports io.github.ititus.math.statistics;
    exports io.github.ititus.math.time;
    exports io.github.ititus.math.vector;
    exports io.github.ititus.parser;
    exports io.github.ititus.precondition;
    exports io.github.ititus.si;
    exports io.github.ititus.si.dimension;
    exports io.github.ititus.si.prefix;
    exports io.github.ititus.si.quantity;
    exports io.github.ititus.si.quantity.type;
    exports io.github.ititus.si.quantity.value;
    exports io.github.ititus.si.unit;
    exports io.github.ititus.si.unit.converter;
    exports io.github.ititus.system;
    exports io.github.ititus.text;
}
